// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: proto/courier.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Courier struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Lat           string                 `protobuf:"bytes,3,opt,name=lat,proto3" json:"lat,omitempty"`
	Long          string                 `protobuf:"bytes,4,opt,name=long,proto3" json:"long,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Courier) Reset() {
	*x = Courier{}
	mi := &file_proto_courier_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Courier) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Courier) ProtoMessage() {}

func (x *Courier) ProtoReflect() protoreflect.Message {
	mi := &file_proto_courier_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Courier.ProtoReflect.Descriptor instead.
func (*Courier) Descriptor() ([]byte, []int) {
	return file_proto_courier_proto_rawDescGZIP(), []int{0}
}

func (x *Courier) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Courier) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Courier) GetLat() string {
	if x != nil {
		return x.Lat
	}
	return ""
}

func (x *Courier) GetLong() string {
	if x != nil {
		return x.Long
	}
	return ""
}

func (x *Courier) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Courier) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type CourierListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Couriers      []*Courier             `protobuf:"bytes,1,rep,name=couriers,proto3" json:"couriers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CourierListResponse) Reset() {
	*x = CourierListResponse{}
	mi := &file_proto_courier_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CourierListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CourierListResponse) ProtoMessage() {}

func (x *CourierListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_courier_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CourierListResponse.ProtoReflect.Descriptor instead.
func (*CourierListResponse) Descriptor() ([]byte, []int) {
	return file_proto_courier_proto_rawDescGZIP(), []int{1}
}

func (x *CourierListResponse) GetCouriers() []*Courier {
	if x != nil {
		return x.Couriers
	}
	return nil
}

type CreateCourierReqeuest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Lat           string                 `protobuf:"bytes,2,opt,name=lat,proto3" json:"lat,omitempty"`
	Long          string                 `protobuf:"bytes,3,opt,name=long,proto3" json:"long,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCourierReqeuest) Reset() {
	*x = CreateCourierReqeuest{}
	mi := &file_proto_courier_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCourierReqeuest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCourierReqeuest) ProtoMessage() {}

func (x *CreateCourierReqeuest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_courier_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCourierReqeuest.ProtoReflect.Descriptor instead.
func (*CreateCourierReqeuest) Descriptor() ([]byte, []int) {
	return file_proto_courier_proto_rawDescGZIP(), []int{2}
}

func (x *CreateCourierReqeuest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CreateCourierReqeuest) GetLat() string {
	if x != nil {
		return x.Lat
	}
	return ""
}

func (x *CreateCourierReqeuest) GetLong() string {
	if x != nil {
		return x.Long
	}
	return ""
}

type UpdateLangLotCourierReqeuest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Lat           string                 `protobuf:"bytes,2,opt,name=lat,proto3" json:"lat,omitempty"`
	Long          string                 `protobuf:"bytes,3,opt,name=long,proto3" json:"long,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateLangLotCourierReqeuest) Reset() {
	*x = UpdateLangLotCourierReqeuest{}
	mi := &file_proto_courier_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateLangLotCourierReqeuest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateLangLotCourierReqeuest) ProtoMessage() {}

func (x *UpdateLangLotCourierReqeuest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_courier_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateLangLotCourierReqeuest.ProtoReflect.Descriptor instead.
func (*UpdateLangLotCourierReqeuest) Descriptor() ([]byte, []int) {
	return file_proto_courier_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateLangLotCourierReqeuest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateLangLotCourierReqeuest) GetLat() string {
	if x != nil {
		return x.Lat
	}
	return ""
}

func (x *UpdateLangLotCourierReqeuest) GetLong() string {
	if x != nil {
		return x.Long
	}
	return ""
}

type DeleteCourierRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteCourierRequest) Reset() {
	*x = DeleteCourierRequest{}
	mi := &file_proto_courier_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteCourierRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCourierRequest) ProtoMessage() {}

func (x *DeleteCourierRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_courier_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCourierRequest.ProtoReflect.Descriptor instead.
func (*DeleteCourierRequest) Descriptor() ([]byte, []int) {
	return file_proto_courier_proto_rawDescGZIP(), []int{4}
}

func (x *DeleteCourierRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteCourierResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteCourierResponse) Reset() {
	*x = DeleteCourierResponse{}
	mi := &file_proto_courier_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteCourierResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCourierResponse) ProtoMessage() {}

func (x *DeleteCourierResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_courier_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCourierResponse.ProtoReflect.Descriptor instead.
func (*DeleteCourierResponse) Descriptor() ([]byte, []int) {
	return file_proto_courier_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteCourierResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type CourierResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Courier       *Courier               `protobuf:"bytes,1,opt,name=Courier,proto3" json:"Courier,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CourierResponse) Reset() {
	*x = CourierResponse{}
	mi := &file_proto_courier_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CourierResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CourierResponse) ProtoMessage() {}

func (x *CourierResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_courier_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CourierResponse.ProtoReflect.Descriptor instead.
func (*CourierResponse) Descriptor() ([]byte, []int) {
	return file_proto_courier_proto_rawDescGZIP(), []int{6}
}

func (x *CourierResponse) GetCourier() *Courier {
	if x != nil {
		return x.Courier
	}
	return nil
}

type GetByIdCourierReqeuest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetByIdCourierReqeuest) Reset() {
	*x = GetByIdCourierReqeuest{}
	mi := &file_proto_courier_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetByIdCourierReqeuest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetByIdCourierReqeuest) ProtoMessage() {}

func (x *GetByIdCourierReqeuest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_courier_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetByIdCourierReqeuest.ProtoReflect.Descriptor instead.
func (*GetByIdCourierReqeuest) Descriptor() ([]byte, []int) {
	return file_proto_courier_proto_rawDescGZIP(), []int{7}
}

func (x *GetByIdCourierReqeuest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetByLongLatCourierReqeuest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Lat           string                 `protobuf:"bytes,1,opt,name=lat,proto3" json:"lat,omitempty"`
	Long          string                 `protobuf:"bytes,2,opt,name=long,proto3" json:"long,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetByLongLatCourierReqeuest) Reset() {
	*x = GetByLongLatCourierReqeuest{}
	mi := &file_proto_courier_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetByLongLatCourierReqeuest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetByLongLatCourierReqeuest) ProtoMessage() {}

func (x *GetByLongLatCourierReqeuest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_courier_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetByLongLatCourierReqeuest.ProtoReflect.Descriptor instead.
func (*GetByLongLatCourierReqeuest) Descriptor() ([]byte, []int) {
	return file_proto_courier_proto_rawDescGZIP(), []int{8}
}

func (x *GetByLongLatCourierReqeuest) GetLat() string {
	if x != nil {
		return x.Lat
	}
	return ""
}

func (x *GetByLongLatCourierReqeuest) GetLong() string {
	if x != nil {
		return x.Long
	}
	return ""
}

var File_proto_courier_proto protoreflect.FileDescriptor

const file_proto_courier_proto_rawDesc = "" +
	"\n" +
	"\x13proto/courier.proto\x12\acourier\x1a\x1fgoogle/protobuf/timestamp.proto\"\xce\x01\n" +
	"\aCourier\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x10\n" +
	"\x03lat\x18\x03 \x01(\tR\x03lat\x12\x12\n" +
	"\x04long\x18\x04 \x01(\tR\x04long\x129\n" +
	"\n" +
	"created_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"C\n" +
	"\x13CourierListResponse\x12,\n" +
	"\bcouriers\x18\x01 \x03(\v2\x10.courier.CourierR\bcouriers\"V\n" +
	"\x15CreateCourierReqeuest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x10\n" +
	"\x03lat\x18\x02 \x01(\tR\x03lat\x12\x12\n" +
	"\x04long\x18\x03 \x01(\tR\x04long\"T\n" +
	"\x1cUpdateLangLotCourierReqeuest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x10\n" +
	"\x03lat\x18\x02 \x01(\tR\x03lat\x12\x12\n" +
	"\x04long\x18\x03 \x01(\tR\x04long\"&\n" +
	"\x14DeleteCourierRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"1\n" +
	"\x15DeleteCourierResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"=\n" +
	"\x0fCourierResponse\x12*\n" +
	"\aCourier\x18\x01 \x01(\v2\x10.courier.CourierR\aCourier\"(\n" +
	"\x16GetByIdCourierReqeuest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"C\n" +
	"\x1bGetByLongLatCourierReqeuest\x12\x10\n" +
	"\x03lat\x18\x01 \x01(\tR\x03lat\x12\x12\n" +
	"\x04long\x18\x02 \x01(\tR\x04long2\x9a\x03\n" +
	"\x0eCourierService\x12I\n" +
	"\rCreateCourier\x12\x1e.courier.CreateCourierReqeuest\x1a\x18.courier.CourierResponse\x12D\n" +
	"\aGetById\x12\x1f.courier.GetByIdCourierReqeuest\x1a\x18.courier.CourierResponse\x12N\n" +
	"\fGetByLongLat\x12$.courier.GetByLongLatCourierReqeuest\x1a\x18.courier.CourierResponse\x12W\n" +
	"\x14UpdateLongLatCourier\x12%.courier.UpdateLangLotCourierReqeuest\x1a\x18.courier.CourierResponse\x12N\n" +
	"\rDeleteCourier\x12\x1d.courier.DeleteCourierRequest\x1a\x1e.courier.DeleteCourierResponseB\x1eZ\x1cinternal/delivery/grpc/pb;pbb\x06proto3"

var (
	file_proto_courier_proto_rawDescOnce sync.Once
	file_proto_courier_proto_rawDescData []byte
)

func file_proto_courier_proto_rawDescGZIP() []byte {
	file_proto_courier_proto_rawDescOnce.Do(func() {
		file_proto_courier_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_courier_proto_rawDesc), len(file_proto_courier_proto_rawDesc)))
	})
	return file_proto_courier_proto_rawDescData
}

var file_proto_courier_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_proto_courier_proto_goTypes = []any{
	(*Courier)(nil),                      // 0: courier.Courier
	(*CourierListResponse)(nil),          // 1: courier.CourierListResponse
	(*CreateCourierReqeuest)(nil),        // 2: courier.CreateCourierReqeuest
	(*UpdateLangLotCourierReqeuest)(nil), // 3: courier.UpdateLangLotCourierReqeuest
	(*DeleteCourierRequest)(nil),         // 4: courier.DeleteCourierRequest
	(*DeleteCourierResponse)(nil),        // 5: courier.DeleteCourierResponse
	(*CourierResponse)(nil),              // 6: courier.CourierResponse
	(*GetByIdCourierReqeuest)(nil),       // 7: courier.GetByIdCourierReqeuest
	(*GetByLongLatCourierReqeuest)(nil),  // 8: courier.GetByLongLatCourierReqeuest
	(*timestamppb.Timestamp)(nil),        // 9: google.protobuf.Timestamp
}
var file_proto_courier_proto_depIdxs = []int32{
	9, // 0: courier.Courier.created_at:type_name -> google.protobuf.Timestamp
	9, // 1: courier.Courier.updated_at:type_name -> google.protobuf.Timestamp
	0, // 2: courier.CourierListResponse.couriers:type_name -> courier.Courier
	0, // 3: courier.CourierResponse.Courier:type_name -> courier.Courier
	2, // 4: courier.CourierService.CreateCourier:input_type -> courier.CreateCourierReqeuest
	7, // 5: courier.CourierService.GetById:input_type -> courier.GetByIdCourierReqeuest
	8, // 6: courier.CourierService.GetByLongLat:input_type -> courier.GetByLongLatCourierReqeuest
	3, // 7: courier.CourierService.UpdateLongLatCourier:input_type -> courier.UpdateLangLotCourierReqeuest
	4, // 8: courier.CourierService.DeleteCourier:input_type -> courier.DeleteCourierRequest
	6, // 9: courier.CourierService.CreateCourier:output_type -> courier.CourierResponse
	6, // 10: courier.CourierService.GetById:output_type -> courier.CourierResponse
	6, // 11: courier.CourierService.GetByLongLat:output_type -> courier.CourierResponse
	6, // 12: courier.CourierService.UpdateLongLatCourier:output_type -> courier.CourierResponse
	5, // 13: courier.CourierService.DeleteCourier:output_type -> courier.DeleteCourierResponse
	9, // [9:14] is the sub-list for method output_type
	4, // [4:9] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_proto_courier_proto_init() }
func file_proto_courier_proto_init() {
	if File_proto_courier_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_courier_proto_rawDesc), len(file_proto_courier_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_courier_proto_goTypes,
		DependencyIndexes: file_proto_courier_proto_depIdxs,
		MessageInfos:      file_proto_courier_proto_msgTypes,
	}.Build()
	File_proto_courier_proto = out.File
	file_proto_courier_proto_goTypes = nil
	file_proto_courier_proto_depIdxs = nil
}
