version: '3.8'


services:
  auth-service:
    build:
      context: ./auth-service
    image: asia-southeast2-docker.pkg.dev/exalted-arcanum-465715-h7/onlinefood-repo/auth-service:latest
    container_name: auth-service
    ports:
      - "50051:50051"
    environment:
      - DATABASE_URI=postgres://postgres:1234@postgres:5432/auth_service?sslmode=disable
      - JWT_SECRET=your_jwt_secret_key
      - GRPC_PORT=50051
      - SMTP_HOST=smtp.gmail.com
      - SMTP_PORT=587
      - SMTP_USER=ruditopujiarso@gmail.com
      - SMTP_PASS=elzi jyjh plqs hbxv
      - SMTP_FROM=ruditopujiarso@gmail.com
      - GOOGLE_API_KEY=AIzaSyADuYB4pe4PPKai6ULrUMVDjUFWxl22afc
      - KAFKA_BROKER=kafka:9092
    depends_on:
      - postgres
      - kafka

  courier-service:
    build:
      context: ./courier-service
    image: asia-southeast2-docker.pkg.dev/exalted-arcanum-465715-h7/onlinefood-repo/courier-service:latest
    container_name: courier-service
    ports:
      - "50052:50052"
    environment:
      - DATABASE_URI=postgres://postgres:1234@postgres:5432/courier_service?sslmode=disable
      - GRPC_PORT=50052
    depends_on:
      - postgres

  food-service:
    build:
      context: ./food-service
    image: asia-southeast2-docker.pkg.dev/exalted-arcanum-465715-h7/onlinefood-repo/food-service:latest
    container_name: food-service
    ports:
      - "50053:50053"
    environment:
      - DATABASE_URI=postgres://postgres:1234@postgres:5432/food_service?sslmode=disable
      - GRPC_PORT=50053
      - KAFKA_BROKER=kafka:9092
      - MERCHANT_SERVICE_ADDR=merchant-service:50054
    depends_on:
      - postgres
      - kafka

  merchant-service:
    build:
      context: ./merchant-service
    image: asia-southeast2-docker.pkg.dev/exalted-arcanum-465715-h7/onlinefood-repo/merchant-service:latest
    container_name: merchant-service
    ports:
      - "50054:50054"
    environment:
      - DATABASE_URI=postgres://postgres:1234@postgres:5432/merchant_service?sslmode=disable
      - GRPC_PORT=50054
      - GOOGLE_API_KEY=AIzaSyADuYB4pe4PPKai6ULrUMVDjUFWxl22afc
    depends_on:
      - postgres
      
  transaction-service:
    build:
      context: ./transaction-service
    image: asia-southeast2-docker.pkg.dev/exalted-arcanum-465715-h7/onlinefood-repo/transaction-service:latest
    container_name: transaction-service
    ports:
      - "50055:50055"
    environment:
      - DATABASE_URI=postgres://postgres:1234@postgres:5432/transaction_service?sslmode=disable
      - GRPC_PORT=50055
      - GOOGLE_API_KEY=AIzaSyADuYB4pe4PPKai6ULrUMVDjUFWxl22afc
      - MIDTRANS_SERVER_KEY=SB-Mid-server-FzH5xlkx-uwmU__xroDdRPUG
      - MIDTRANS_CLIENT_KEY=SB-Mid-client-mMqK1sLFvF
      - MIDTRANS_ENV=sandbox
      - COURIER_SERVICE_ADDR=courier-service:50052
      - MERCHANT_SERVICE_ADDR=merchant-service:50054
    depends_on:
      - postgres

  gateway-service:
    build:
      context: ./gateway-service
    container_name: gateway-service
    ports:
      - "8032:8032"
    image: asia-southeast2-docker.pkg.dev/exalted-arcanum-465715-h7/onlinefood-repo/gateway-service:latest
    environment:
      - AUTH_SERVICE_URL=auth-service:50051
      - COURIER_SERVICE_URL=courier-service:50052
      - FOOD_SERVICE_URL=food-service:50053
      - MERCHANT_SERVICE_URL=merchant-service:50054
      - TRANSACTION_SERVICE_URL=transaction-service:50055
      - JWT_SECRET=your_jwt_secret_key
      - PORT=8032
    depends_on:
      - auth-service
      - courier-service
      - food-service
      - merchant-service
      - transaction-service

  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./postgres-init:/docker-entrypoint-initdb.d

  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
      - "29092:29092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

volumes:
  pg_data:
