version: '3.8'

services:
  auth-service:
    build:
      context: ./auth-service
    container_name: auth-service
    ports:
      - "50051:50051"
    environment:
      - DATABASE_URI=postgres://postgres:1234@postgres:5432/auth_service?sslmode=disable
      - JWT_SECRET=your_jwt_secret_key
      - GRPC_PORT=50051
      - SMTP_HOST=smtp.gmail.com
      - SMTP_PORT=587
      - SMTP_USER=your-gmail@gmail.com
      - SMTP_PASS=isi-dengan-app-password
      - SMTP_FROM=your-gmail@gmail.com
    depends_on:
      - postgres

  courier-service:
    build:
      context: ./courier-service
    container_name: courier-service
    ports:
      - "50052:50052"
    environment:
      - DATABASE_URI=postgres://postgres:1234@postgres:5432/courier_service?sslmode=disable
      - GRPC_PORT=50052
    depends_on:
      - postgres

  food-service:
    build:
      context: ./food-service
    container_name: food-service
    ports:
      - "50053:50053"
    environment:
      - DATABASE_URI=postgres://postgres:1234@postgres:5432/food_service?sslmode=disable
      - GRPC_PORT=50053
    depends_on:
      - postgres

  merchant-service:
    build:
      context: ./merchant-service
    container_name: merchant-service
    ports:
      - "50054:50054"
    environment:
      - DATABASE_URI=postgres://postgres:1234@postgres:5432/merchant_service?sslmode=disable
      - GRPC_PORT=50054
    depends_on:
      - postgres

  transaction-service:
    build:
      context: ./transaction-service
    container_name: transaction-service
    ports:
      - "50055:50055"
    environment:
      - DATABASE_URI=postgres://postgres:1234@postgres:5432/transaction_service?sslmode=disable
      - GRPC_PORT=50055
    depends_on:
      - postgres

  # gateway-service:
  #   build:
  #     context: ./gateway-service
  #   container_name: gateway-service
  #   ports:
  #     - "8081:8081"
  #   environment:
  #     - AUTH_GRPC_HOST=auth-service:50051
  #     - COURIER_GRPC_HOST=courier-service:50052
  #     - FOOD_GRPC_HOST=food-service:50053
  #     - MERCHANT_GRPC_HOST=merchant-service:50054
  #     - TRANSACTION_GRPC_HOST=transaction-service:50055
  #     - GATEWAY_PORT=8081
  #   depends_on:
  #     - auth-service
  #     - courier-service
  #     - food-service
  #     - merchant-service
  #     - transaction-service

  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data:
