// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: proto/food.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Food struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	MerchantId    string                 `protobuf:"bytes,2,opt,name=merchant_id,json=merchantId,proto3" json:"merchant_id,omitempty"`
	NameFoods     string                 `protobuf:"bytes,3,opt,name=name_foods,json=nameFoods,proto3" json:"name_foods,omitempty"`
	Price         int64                  `protobuf:"varint,4,opt,name=price,proto3" json:"price,omitempty"`
	Availability  string                 `protobuf:"bytes,5,opt,name=availability,proto3" json:"availability,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Food) Reset() {
	*x = Food{}
	mi := &file_proto_food_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Food) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Food) ProtoMessage() {}

func (x *Food) ProtoReflect() protoreflect.Message {
	mi := &file_proto_food_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Food.ProtoReflect.Descriptor instead.
func (*Food) Descriptor() ([]byte, []int) {
	return file_proto_food_proto_rawDescGZIP(), []int{0}
}

func (x *Food) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Food) GetMerchantId() string {
	if x != nil {
		return x.MerchantId
	}
	return ""
}

func (x *Food) GetNameFoods() string {
	if x != nil {
		return x.NameFoods
	}
	return ""
}

func (x *Food) GetPrice() int64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *Food) GetAvailability() string {
	if x != nil {
		return x.Availability
	}
	return ""
}

func (x *Food) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Food) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type FoodListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Foods         []*Food                `protobuf:"bytes,1,rep,name=foods,proto3" json:"foods,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FoodListResponse) Reset() {
	*x = FoodListResponse{}
	mi := &file_proto_food_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FoodListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FoodListResponse) ProtoMessage() {}

func (x *FoodListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_food_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FoodListResponse.ProtoReflect.Descriptor instead.
func (*FoodListResponse) Descriptor() ([]byte, []int) {
	return file_proto_food_proto_rawDescGZIP(), []int{1}
}

func (x *FoodListResponse) GetFoods() []*Food {
	if x != nil {
		return x.Foods
	}
	return nil
}

type CreateFoodReqeuest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MerchantId    string                 `protobuf:"bytes,1,opt,name=merchant_id,json=merchantId,proto3" json:"merchant_id,omitempty"`
	NameFoods     string                 `protobuf:"bytes,2,opt,name=name_foods,json=nameFoods,proto3" json:"name_foods,omitempty"`
	Price         int64                  `protobuf:"varint,3,opt,name=price,proto3" json:"price,omitempty"`
	Availability  string                 `protobuf:"bytes,4,opt,name=availability,proto3" json:"availability,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateFoodReqeuest) Reset() {
	*x = CreateFoodReqeuest{}
	mi := &file_proto_food_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateFoodReqeuest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateFoodReqeuest) ProtoMessage() {}

func (x *CreateFoodReqeuest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_food_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateFoodReqeuest.ProtoReflect.Descriptor instead.
func (*CreateFoodReqeuest) Descriptor() ([]byte, []int) {
	return file_proto_food_proto_rawDescGZIP(), []int{2}
}

func (x *CreateFoodReqeuest) GetMerchantId() string {
	if x != nil {
		return x.MerchantId
	}
	return ""
}

func (x *CreateFoodReqeuest) GetNameFoods() string {
	if x != nil {
		return x.NameFoods
	}
	return ""
}

func (x *CreateFoodReqeuest) GetPrice() int64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *CreateFoodReqeuest) GetAvailability() string {
	if x != nil {
		return x.Availability
	}
	return ""
}

type UpdateFoodReqeuest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	MerchantId    string                 `protobuf:"bytes,2,opt,name=merchant_id,json=merchantId,proto3" json:"merchant_id,omitempty"`
	NameFoods     string                 `protobuf:"bytes,3,opt,name=name_foods,json=nameFoods,proto3" json:"name_foods,omitempty"`
	Price         int64                  `protobuf:"varint,4,opt,name=price,proto3" json:"price,omitempty"`
	Availability  string                 `protobuf:"bytes,5,opt,name=availability,proto3" json:"availability,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateFoodReqeuest) Reset() {
	*x = UpdateFoodReqeuest{}
	mi := &file_proto_food_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateFoodReqeuest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateFoodReqeuest) ProtoMessage() {}

func (x *UpdateFoodReqeuest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_food_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateFoodReqeuest.ProtoReflect.Descriptor instead.
func (*UpdateFoodReqeuest) Descriptor() ([]byte, []int) {
	return file_proto_food_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateFoodReqeuest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateFoodReqeuest) GetMerchantId() string {
	if x != nil {
		return x.MerchantId
	}
	return ""
}

func (x *UpdateFoodReqeuest) GetNameFoods() string {
	if x != nil {
		return x.NameFoods
	}
	return ""
}

func (x *UpdateFoodReqeuest) GetPrice() int64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *UpdateFoodReqeuest) GetAvailability() string {
	if x != nil {
		return x.Availability
	}
	return ""
}

type DeleteFoodRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteFoodRequest) Reset() {
	*x = DeleteFoodRequest{}
	mi := &file_proto_food_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteFoodRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteFoodRequest) ProtoMessage() {}

func (x *DeleteFoodRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_food_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteFoodRequest.ProtoReflect.Descriptor instead.
func (*DeleteFoodRequest) Descriptor() ([]byte, []int) {
	return file_proto_food_proto_rawDescGZIP(), []int{4}
}

func (x *DeleteFoodRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteFoodResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteFoodResponse) Reset() {
	*x = DeleteFoodResponse{}
	mi := &file_proto_food_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteFoodResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteFoodResponse) ProtoMessage() {}

func (x *DeleteFoodResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_food_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteFoodResponse.ProtoReflect.Descriptor instead.
func (*DeleteFoodResponse) Descriptor() ([]byte, []int) {
	return file_proto_food_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteFoodResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type FoodResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Food          *Food                  `protobuf:"bytes,1,opt,name=Food,proto3" json:"Food,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FoodResponse) Reset() {
	*x = FoodResponse{}
	mi := &file_proto_food_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FoodResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FoodResponse) ProtoMessage() {}

func (x *FoodResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_food_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FoodResponse.ProtoReflect.Descriptor instead.
func (*FoodResponse) Descriptor() ([]byte, []int) {
	return file_proto_food_proto_rawDescGZIP(), []int{6}
}

func (x *FoodResponse) GetFood() *Food {
	if x != nil {
		return x.Food
	}
	return nil
}

type GetByIdFoodReqeuest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetByIdFoodReqeuest) Reset() {
	*x = GetByIdFoodReqeuest{}
	mi := &file_proto_food_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetByIdFoodReqeuest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetByIdFoodReqeuest) ProtoMessage() {}

func (x *GetByIdFoodReqeuest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_food_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetByIdFoodReqeuest.ProtoReflect.Descriptor instead.
func (*GetByIdFoodReqeuest) Descriptor() ([]byte, []int) {
	return file_proto_food_proto_rawDescGZIP(), []int{7}
}

func (x *GetByIdFoodReqeuest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_proto_food_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_proto_food_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_proto_food_proto_rawDescGZIP(), []int{8}
}

var File_proto_food_proto protoreflect.FileDescriptor

const file_proto_food_proto_rawDesc = "" +
	"\n" +
	"\x10proto/food.proto\x12\x04food\x1a\x1fgoogle/protobuf/timestamp.proto\"\x86\x02\n" +
	"\x04Food\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1f\n" +
	"\vmerchant_id\x18\x02 \x01(\tR\n" +
	"merchantId\x12\x1d\n" +
	"\n" +
	"name_foods\x18\x03 \x01(\tR\tnameFoods\x12\x14\n" +
	"\x05price\x18\x04 \x01(\x03R\x05price\x12\"\n" +
	"\favailability\x18\x05 \x01(\tR\favailability\x129\n" +
	"\n" +
	"created_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"4\n" +
	"\x10FoodListResponse\x12 \n" +
	"\x05foods\x18\x01 \x03(\v2\n" +
	".food.FoodR\x05foods\"\x8e\x01\n" +
	"\x12CreateFoodReqeuest\x12\x1f\n" +
	"\vmerchant_id\x18\x01 \x01(\tR\n" +
	"merchantId\x12\x1d\n" +
	"\n" +
	"name_foods\x18\x02 \x01(\tR\tnameFoods\x12\x14\n" +
	"\x05price\x18\x03 \x01(\x03R\x05price\x12\"\n" +
	"\favailability\x18\x04 \x01(\tR\favailability\"\x9e\x01\n" +
	"\x12UpdateFoodReqeuest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1f\n" +
	"\vmerchant_id\x18\x02 \x01(\tR\n" +
	"merchantId\x12\x1d\n" +
	"\n" +
	"name_foods\x18\x03 \x01(\tR\tnameFoods\x12\x14\n" +
	"\x05price\x18\x04 \x01(\x03R\x05price\x12\"\n" +
	"\favailability\x18\x05 \x01(\tR\favailability\"#\n" +
	"\x11DeleteFoodRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\".\n" +
	"\x12DeleteFoodResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\".\n" +
	"\fFoodResponse\x12\x1e\n" +
	"\x04Food\x18\x01 \x01(\v2\n" +
	".food.FoodR\x04Food\"%\n" +
	"\x13GetByIdFoodReqeuest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\a\n" +
	"\x05Empty2\xb3\x02\n" +
	"\vFoodService\x12:\n" +
	"\n" +
	"CreateFood\x12\x18.food.CreateFoodReqeuest\x1a\x12.food.FoodResponse\x12-\n" +
	"\n" +
	"GetAllFood\x12\v.food.Empty\x1a\x12.food.FoodResponse\x12<\n" +
	"\vGetByIdFood\x12\x19.food.GetByIdFoodReqeuest\x1a\x12.food.FoodResponse\x12:\n" +
	"\n" +
	"UpdateFood\x12\x18.food.UpdateFoodReqeuest\x1a\x12.food.FoodResponse\x12?\n" +
	"\n" +
	"DeleteFood\x12\x17.food.DeleteFoodRequest\x1a\x18.food.DeleteFoodResponseB\x1eZ\x1cinternal/delivery/grpc/pb;pbb\x06proto3"

var (
	file_proto_food_proto_rawDescOnce sync.Once
	file_proto_food_proto_rawDescData []byte
)

func file_proto_food_proto_rawDescGZIP() []byte {
	file_proto_food_proto_rawDescOnce.Do(func() {
		file_proto_food_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_food_proto_rawDesc), len(file_proto_food_proto_rawDesc)))
	})
	return file_proto_food_proto_rawDescData
}

var file_proto_food_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_proto_food_proto_goTypes = []any{
	(*Food)(nil),                  // 0: food.Food
	(*FoodListResponse)(nil),      // 1: food.FoodListResponse
	(*CreateFoodReqeuest)(nil),    // 2: food.CreateFoodReqeuest
	(*UpdateFoodReqeuest)(nil),    // 3: food.UpdateFoodReqeuest
	(*DeleteFoodRequest)(nil),     // 4: food.DeleteFoodRequest
	(*DeleteFoodResponse)(nil),    // 5: food.DeleteFoodResponse
	(*FoodResponse)(nil),          // 6: food.FoodResponse
	(*GetByIdFoodReqeuest)(nil),   // 7: food.GetByIdFoodReqeuest
	(*Empty)(nil),                 // 8: food.Empty
	(*timestamppb.Timestamp)(nil), // 9: google.protobuf.Timestamp
}
var file_proto_food_proto_depIdxs = []int32{
	9, // 0: food.Food.created_at:type_name -> google.protobuf.Timestamp
	9, // 1: food.Food.updated_at:type_name -> google.protobuf.Timestamp
	0, // 2: food.FoodListResponse.foods:type_name -> food.Food
	0, // 3: food.FoodResponse.Food:type_name -> food.Food
	2, // 4: food.FoodService.CreateFood:input_type -> food.CreateFoodReqeuest
	8, // 5: food.FoodService.GetAllFood:input_type -> food.Empty
	7, // 6: food.FoodService.GetByIdFood:input_type -> food.GetByIdFoodReqeuest
	3, // 7: food.FoodService.UpdateFood:input_type -> food.UpdateFoodReqeuest
	4, // 8: food.FoodService.DeleteFood:input_type -> food.DeleteFoodRequest
	6, // 9: food.FoodService.CreateFood:output_type -> food.FoodResponse
	6, // 10: food.FoodService.GetAllFood:output_type -> food.FoodResponse
	6, // 11: food.FoodService.GetByIdFood:output_type -> food.FoodResponse
	6, // 12: food.FoodService.UpdateFood:output_type -> food.FoodResponse
	5, // 13: food.FoodService.DeleteFood:output_type -> food.DeleteFoodResponse
	9, // [9:14] is the sub-list for method output_type
	4, // [4:9] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_proto_food_proto_init() }
func file_proto_food_proto_init() {
	if File_proto_food_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_food_proto_rawDesc), len(file_proto_food_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_food_proto_goTypes,
		DependencyIndexes: file_proto_food_proto_depIdxs,
		MessageInfos:      file_proto_food_proto_msgTypes,
	}.Build()
	File_proto_food_proto = out.File
	file_proto_food_proto_goTypes = nil
	file_proto_food_proto_depIdxs = nil
}
