version: '3.8'

services:
  jenkins:
    build: .
    container_name: jenkins
    ports:
      - "8055:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always

volumes:
  jenkins_home:
