// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: proto/cart.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Cart struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	MerchantId    int64                  `protobuf:"varint,2,opt,name=merchant_id,json=merchantId,proto3" json:"merchant_id,omitempty"`
	FoodId        int64                  `protobuf:"varint,3,opt,name=food_id,json=foodId,proto3" json:"food_id,omitempty"`
	Qty           int64                  `protobuf:"varint,4,opt,name=qty,proto3" json:"qty,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Cart) Reset() {
	*x = Cart{}
	mi := &file_proto_cart_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Cart) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Cart) ProtoMessage() {}

func (x *Cart) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cart_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Cart.ProtoReflect.Descriptor instead.
func (*Cart) Descriptor() ([]byte, []int) {
	return file_proto_cart_proto_rawDescGZIP(), []int{0}
}

func (x *Cart) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Cart) GetMerchantId() int64 {
	if x != nil {
		return x.MerchantId
	}
	return 0
}

func (x *Cart) GetFoodId() int64 {
	if x != nil {
		return x.FoodId
	}
	return 0
}

func (x *Cart) GetQty() int64 {
	if x != nil {
		return x.Qty
	}
	return 0
}

func (x *Cart) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Cart) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type CartListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Carts         []*Cart                `protobuf:"bytes,1,rep,name=carts,proto3" json:"carts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CartListResponse) Reset() {
	*x = CartListResponse{}
	mi := &file_proto_cart_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CartListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CartListResponse) ProtoMessage() {}

func (x *CartListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cart_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CartListResponse.ProtoReflect.Descriptor instead.
func (*CartListResponse) Descriptor() ([]byte, []int) {
	return file_proto_cart_proto_rawDescGZIP(), []int{1}
}

func (x *CartListResponse) GetCarts() []*Cart {
	if x != nil {
		return x.Carts
	}
	return nil
}

type CreateCartReqeuest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MerchantId    int64                  `protobuf:"varint,1,opt,name=merchant_id,json=merchantId,proto3" json:"merchant_id,omitempty"`
	FoodId        int64                  `protobuf:"varint,2,opt,name=food_id,json=foodId,proto3" json:"food_id,omitempty"`
	Qty           int64                  `protobuf:"varint,3,opt,name=qty,proto3" json:"qty,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCartReqeuest) Reset() {
	*x = CreateCartReqeuest{}
	mi := &file_proto_cart_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCartReqeuest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCartReqeuest) ProtoMessage() {}

func (x *CreateCartReqeuest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cart_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCartReqeuest.ProtoReflect.Descriptor instead.
func (*CreateCartReqeuest) Descriptor() ([]byte, []int) {
	return file_proto_cart_proto_rawDescGZIP(), []int{2}
}

func (x *CreateCartReqeuest) GetMerchantId() int64 {
	if x != nil {
		return x.MerchantId
	}
	return 0
}

func (x *CreateCartReqeuest) GetFoodId() int64 {
	if x != nil {
		return x.FoodId
	}
	return 0
}

func (x *CreateCartReqeuest) GetQty() int64 {
	if x != nil {
		return x.Qty
	}
	return 0
}

type UpdateCartReqeuest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	MerchantId    int64                  `protobuf:"varint,2,opt,name=merchant_id,json=merchantId,proto3" json:"merchant_id,omitempty"`
	FoodId        int64                  `protobuf:"varint,3,opt,name=food_id,json=foodId,proto3" json:"food_id,omitempty"`
	Qty           int64                  `protobuf:"varint,4,opt,name=qty,proto3" json:"qty,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateCartReqeuest) Reset() {
	*x = UpdateCartReqeuest{}
	mi := &file_proto_cart_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateCartReqeuest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCartReqeuest) ProtoMessage() {}

func (x *UpdateCartReqeuest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cart_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCartReqeuest.ProtoReflect.Descriptor instead.
func (*UpdateCartReqeuest) Descriptor() ([]byte, []int) {
	return file_proto_cart_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateCartReqeuest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateCartReqeuest) GetMerchantId() int64 {
	if x != nil {
		return x.MerchantId
	}
	return 0
}

func (x *UpdateCartReqeuest) GetFoodId() int64 {
	if x != nil {
		return x.FoodId
	}
	return 0
}

func (x *UpdateCartReqeuest) GetQty() int64 {
	if x != nil {
		return x.Qty
	}
	return 0
}

type DeleteCartRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteCartRequest) Reset() {
	*x = DeleteCartRequest{}
	mi := &file_proto_cart_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteCartRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCartRequest) ProtoMessage() {}

func (x *DeleteCartRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cart_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCartRequest.ProtoReflect.Descriptor instead.
func (*DeleteCartRequest) Descriptor() ([]byte, []int) {
	return file_proto_cart_proto_rawDescGZIP(), []int{4}
}

func (x *DeleteCartRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteCartResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteCartResponse) Reset() {
	*x = DeleteCartResponse{}
	mi := &file_proto_cart_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteCartResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCartResponse) ProtoMessage() {}

func (x *DeleteCartResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cart_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCartResponse.ProtoReflect.Descriptor instead.
func (*DeleteCartResponse) Descriptor() ([]byte, []int) {
	return file_proto_cart_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteCartResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type CartResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cart          *Cart                  `protobuf:"bytes,1,opt,name=Cart,proto3" json:"Cart,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CartResponse) Reset() {
	*x = CartResponse{}
	mi := &file_proto_cart_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CartResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CartResponse) ProtoMessage() {}

func (x *CartResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cart_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CartResponse.ProtoReflect.Descriptor instead.
func (*CartResponse) Descriptor() ([]byte, []int) {
	return file_proto_cart_proto_rawDescGZIP(), []int{6}
}

func (x *CartResponse) GetCart() *Cart {
	if x != nil {
		return x.Cart
	}
	return nil
}

type GetByIdCartReqeuest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetByIdCartReqeuest) Reset() {
	*x = GetByIdCartReqeuest{}
	mi := &file_proto_cart_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetByIdCartReqeuest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetByIdCartReqeuest) ProtoMessage() {}

func (x *GetByIdCartReqeuest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cart_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetByIdCartReqeuest.ProtoReflect.Descriptor instead.
func (*GetByIdCartReqeuest) Descriptor() ([]byte, []int) {
	return file_proto_cart_proto_rawDescGZIP(), []int{7}
}

func (x *GetByIdCartReqeuest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type EmptyCart struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmptyCart) Reset() {
	*x = EmptyCart{}
	mi := &file_proto_cart_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmptyCart) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmptyCart) ProtoMessage() {}

func (x *EmptyCart) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cart_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmptyCart.ProtoReflect.Descriptor instead.
func (*EmptyCart) Descriptor() ([]byte, []int) {
	return file_proto_cart_proto_rawDescGZIP(), []int{8}
}

var File_proto_cart_proto protoreflect.FileDescriptor

const file_proto_cart_proto_rawDesc = "" +
	"\n" +
	"\x10proto/cart.proto\x12\x04cart\x1a\x1fgoogle/protobuf/timestamp.proto\"\xd8\x01\n" +
	"\x04Cart\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1f\n" +
	"\vmerchant_id\x18\x02 \x01(\x03R\n" +
	"merchantId\x12\x17\n" +
	"\afood_id\x18\x03 \x01(\x03R\x06foodId\x12\x10\n" +
	"\x03qty\x18\x04 \x01(\x03R\x03qty\x129\n" +
	"\n" +
	"created_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"4\n" +
	"\x10CartListResponse\x12 \n" +
	"\x05carts\x18\x01 \x03(\v2\n" +
	".cart.CartR\x05carts\"`\n" +
	"\x12CreateCartReqeuest\x12\x1f\n" +
	"\vmerchant_id\x18\x01 \x01(\x03R\n" +
	"merchantId\x12\x17\n" +
	"\afood_id\x18\x02 \x01(\x03R\x06foodId\x12\x10\n" +
	"\x03qty\x18\x03 \x01(\x03R\x03qty\"p\n" +
	"\x12UpdateCartReqeuest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1f\n" +
	"\vmerchant_id\x18\x02 \x01(\x03R\n" +
	"merchantId\x12\x17\n" +
	"\afood_id\x18\x03 \x01(\x03R\x06foodId\x12\x10\n" +
	"\x03qty\x18\x04 \x01(\x03R\x03qty\"#\n" +
	"\x11DeleteCartRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\".\n" +
	"\x12DeleteCartResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\".\n" +
	"\fCartResponse\x12\x1e\n" +
	"\x04Cart\x18\x01 \x01(\v2\n" +
	".cart.CartR\x04Cart\"%\n" +
	"\x13GetByIdCartReqeuest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\v\n" +
	"\tEmptyCart2\xb7\x02\n" +
	"\vCartService\x12:\n" +
	"\n" +
	"CreateCart\x12\x18.cart.CreateCartReqeuest\x1a\x12.cart.CartResponse\x121\n" +
	"\n" +
	"GetAllCart\x12\x0f.cart.EmptyCart\x1a\x12.cart.CartResponse\x12<\n" +
	"\vGetByIdCart\x12\x19.cart.GetByIdCartReqeuest\x1a\x12.cart.CartResponse\x12:\n" +
	"\n" +
	"UpdateCart\x12\x18.cart.UpdateCartReqeuest\x1a\x12.cart.CartResponse\x12?\n" +
	"\n" +
	"DeleteCart\x12\x17.cart.DeleteCartRequest\x1a\x18.cart.DeleteCartResponseB\x1eZ\x1cinternal/delivery/grpc/pb;pbb\x06proto3"

var (
	file_proto_cart_proto_rawDescOnce sync.Once
	file_proto_cart_proto_rawDescData []byte
)

func file_proto_cart_proto_rawDescGZIP() []byte {
	file_proto_cart_proto_rawDescOnce.Do(func() {
		file_proto_cart_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_cart_proto_rawDesc), len(file_proto_cart_proto_rawDesc)))
	})
	return file_proto_cart_proto_rawDescData
}

var file_proto_cart_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_proto_cart_proto_goTypes = []any{
	(*Cart)(nil),                  // 0: cart.Cart
	(*CartListResponse)(nil),      // 1: cart.CartListResponse
	(*CreateCartReqeuest)(nil),    // 2: cart.CreateCartReqeuest
	(*UpdateCartReqeuest)(nil),    // 3: cart.UpdateCartReqeuest
	(*DeleteCartRequest)(nil),     // 4: cart.DeleteCartRequest
	(*DeleteCartResponse)(nil),    // 5: cart.DeleteCartResponse
	(*CartResponse)(nil),          // 6: cart.CartResponse
	(*GetByIdCartReqeuest)(nil),   // 7: cart.GetByIdCartReqeuest
	(*EmptyCart)(nil),             // 8: cart.EmptyCart
	(*timestamppb.Timestamp)(nil), // 9: google.protobuf.Timestamp
}
var file_proto_cart_proto_depIdxs = []int32{
	9, // 0: cart.Cart.created_at:type_name -> google.protobuf.Timestamp
	9, // 1: cart.Cart.updated_at:type_name -> google.protobuf.Timestamp
	0, // 2: cart.CartListResponse.carts:type_name -> cart.Cart
	0, // 3: cart.CartResponse.Cart:type_name -> cart.Cart
	2, // 4: cart.CartService.CreateCart:input_type -> cart.CreateCartReqeuest
	8, // 5: cart.CartService.GetAllCart:input_type -> cart.EmptyCart
	7, // 6: cart.CartService.GetByIdCart:input_type -> cart.GetByIdCartReqeuest
	3, // 7: cart.CartService.UpdateCart:input_type -> cart.UpdateCartReqeuest
	4, // 8: cart.CartService.DeleteCart:input_type -> cart.DeleteCartRequest
	6, // 9: cart.CartService.CreateCart:output_type -> cart.CartResponse
	6, // 10: cart.CartService.GetAllCart:output_type -> cart.CartResponse
	6, // 11: cart.CartService.GetByIdCart:output_type -> cart.CartResponse
	6, // 12: cart.CartService.UpdateCart:output_type -> cart.CartResponse
	5, // 13: cart.CartService.DeleteCart:output_type -> cart.DeleteCartResponse
	9, // [9:14] is the sub-list for method output_type
	4, // [4:9] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_proto_cart_proto_init() }
func file_proto_cart_proto_init() {
	if File_proto_cart_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_cart_proto_rawDesc), len(file_proto_cart_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_cart_proto_goTypes,
		DependencyIndexes: file_proto_cart_proto_depIdxs,
		MessageInfos:      file_proto_cart_proto_msgTypes,
	}.Build()
	File_proto_cart_proto = out.File
	file_proto_cart_proto_goTypes = nil
	file_proto_cart_proto_depIdxs = nil
}
