// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: proto/transaction_detail.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TransactionDetail struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	TransactionId string                 `protobuf:"bytes,2,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	FoodId        string                 `protobuf:"bytes,3,opt,name=food_id,json=foodId,proto3" json:"food_id,omitempty"`
	Price         int64                  `protobuf:"varint,4,opt,name=price,proto3" json:"price,omitempty"`
	Qty           int64                  `protobuf:"varint,5,opt,name=qty,proto3" json:"qty,omitempty"`
	Total         int64                  `protobuf:"varint,6,opt,name=total,proto3" json:"total,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransactionDetail) Reset() {
	*x = TransactionDetail{}
	mi := &file_proto_transaction_detail_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransactionDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransactionDetail) ProtoMessage() {}

func (x *TransactionDetail) ProtoReflect() protoreflect.Message {
	mi := &file_proto_transaction_detail_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransactionDetail.ProtoReflect.Descriptor instead.
func (*TransactionDetail) Descriptor() ([]byte, []int) {
	return file_proto_transaction_detail_proto_rawDescGZIP(), []int{0}
}

func (x *TransactionDetail) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *TransactionDetail) GetTransactionId() string {
	if x != nil {
		return x.TransactionId
	}
	return ""
}

func (x *TransactionDetail) GetFoodId() string {
	if x != nil {
		return x.FoodId
	}
	return ""
}

func (x *TransactionDetail) GetPrice() int64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *TransactionDetail) GetQty() int64 {
	if x != nil {
		return x.Qty
	}
	return 0
}

func (x *TransactionDetail) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *TransactionDetail) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *TransactionDetail) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type TransactionDetailListResponse struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	TransactionDetails []*TransactionDetail   `protobuf:"bytes,1,rep,name=transaction_details,json=transactionDetails,proto3" json:"transaction_details,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *TransactionDetailListResponse) Reset() {
	*x = TransactionDetailListResponse{}
	mi := &file_proto_transaction_detail_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransactionDetailListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransactionDetailListResponse) ProtoMessage() {}

func (x *TransactionDetailListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_transaction_detail_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransactionDetailListResponse.ProtoReflect.Descriptor instead.
func (*TransactionDetailListResponse) Descriptor() ([]byte, []int) {
	return file_proto_transaction_detail_proto_rawDescGZIP(), []int{1}
}

func (x *TransactionDetailListResponse) GetTransactionDetails() []*TransactionDetail {
	if x != nil {
		return x.TransactionDetails
	}
	return nil
}

type CreateTransactionDetailReqeuest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TransactionId string                 `protobuf:"bytes,1,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	FoodId        string                 `protobuf:"bytes,2,opt,name=food_id,json=foodId,proto3" json:"food_id,omitempty"`
	Price         int64                  `protobuf:"varint,3,opt,name=price,proto3" json:"price,omitempty"`
	Qty           int64                  `protobuf:"varint,4,opt,name=qty,proto3" json:"qty,omitempty"`
	Total         int64                  `protobuf:"varint,5,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTransactionDetailReqeuest) Reset() {
	*x = CreateTransactionDetailReqeuest{}
	mi := &file_proto_transaction_detail_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTransactionDetailReqeuest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTransactionDetailReqeuest) ProtoMessage() {}

func (x *CreateTransactionDetailReqeuest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_transaction_detail_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTransactionDetailReqeuest.ProtoReflect.Descriptor instead.
func (*CreateTransactionDetailReqeuest) Descriptor() ([]byte, []int) {
	return file_proto_transaction_detail_proto_rawDescGZIP(), []int{2}
}

func (x *CreateTransactionDetailReqeuest) GetTransactionId() string {
	if x != nil {
		return x.TransactionId
	}
	return ""
}

func (x *CreateTransactionDetailReqeuest) GetFoodId() string {
	if x != nil {
		return x.FoodId
	}
	return ""
}

func (x *CreateTransactionDetailReqeuest) GetPrice() int64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *CreateTransactionDetailReqeuest) GetQty() int64 {
	if x != nil {
		return x.Qty
	}
	return 0
}

func (x *CreateTransactionDetailReqeuest) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

type UpdateTransactionDetailReqeuest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	TransactionId string                 `protobuf:"bytes,2,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	FoodId        string                 `protobuf:"bytes,3,opt,name=food_id,json=foodId,proto3" json:"food_id,omitempty"`
	Price         int64                  `protobuf:"varint,4,opt,name=price,proto3" json:"price,omitempty"`
	Qty           int64                  `protobuf:"varint,5,opt,name=qty,proto3" json:"qty,omitempty"`
	Total         int64                  `protobuf:"varint,6,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateTransactionDetailReqeuest) Reset() {
	*x = UpdateTransactionDetailReqeuest{}
	mi := &file_proto_transaction_detail_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateTransactionDetailReqeuest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTransactionDetailReqeuest) ProtoMessage() {}

func (x *UpdateTransactionDetailReqeuest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_transaction_detail_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTransactionDetailReqeuest.ProtoReflect.Descriptor instead.
func (*UpdateTransactionDetailReqeuest) Descriptor() ([]byte, []int) {
	return file_proto_transaction_detail_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateTransactionDetailReqeuest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateTransactionDetailReqeuest) GetTransactionId() string {
	if x != nil {
		return x.TransactionId
	}
	return ""
}

func (x *UpdateTransactionDetailReqeuest) GetFoodId() string {
	if x != nil {
		return x.FoodId
	}
	return ""
}

func (x *UpdateTransactionDetailReqeuest) GetPrice() int64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *UpdateTransactionDetailReqeuest) GetQty() int64 {
	if x != nil {
		return x.Qty
	}
	return 0
}

func (x *UpdateTransactionDetailReqeuest) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

type DeleteTransactionDetailRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteTransactionDetailRequest) Reset() {
	*x = DeleteTransactionDetailRequest{}
	mi := &file_proto_transaction_detail_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteTransactionDetailRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTransactionDetailRequest) ProtoMessage() {}

func (x *DeleteTransactionDetailRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_transaction_detail_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteTransactionDetailRequest.ProtoReflect.Descriptor instead.
func (*DeleteTransactionDetailRequest) Descriptor() ([]byte, []int) {
	return file_proto_transaction_detail_proto_rawDescGZIP(), []int{4}
}

func (x *DeleteTransactionDetailRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteTransactionDetailResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteTransactionDetailResponse) Reset() {
	*x = DeleteTransactionDetailResponse{}
	mi := &file_proto_transaction_detail_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteTransactionDetailResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTransactionDetailResponse) ProtoMessage() {}

func (x *DeleteTransactionDetailResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_transaction_detail_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteTransactionDetailResponse.ProtoReflect.Descriptor instead.
func (*DeleteTransactionDetailResponse) Descriptor() ([]byte, []int) {
	return file_proto_transaction_detail_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteTransactionDetailResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type TransactionDetailResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	TransactionDetail *TransactionDetail     `protobuf:"bytes,1,opt,name=TransactionDetail,proto3" json:"TransactionDetail,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *TransactionDetailResponse) Reset() {
	*x = TransactionDetailResponse{}
	mi := &file_proto_transaction_detail_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransactionDetailResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransactionDetailResponse) ProtoMessage() {}

func (x *TransactionDetailResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_transaction_detail_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransactionDetailResponse.ProtoReflect.Descriptor instead.
func (*TransactionDetailResponse) Descriptor() ([]byte, []int) {
	return file_proto_transaction_detail_proto_rawDescGZIP(), []int{6}
}

func (x *TransactionDetailResponse) GetTransactionDetail() *TransactionDetail {
	if x != nil {
		return x.TransactionDetail
	}
	return nil
}

type GetByIdTransactionDetailReqeuest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetByIdTransactionDetailReqeuest) Reset() {
	*x = GetByIdTransactionDetailReqeuest{}
	mi := &file_proto_transaction_detail_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetByIdTransactionDetailReqeuest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetByIdTransactionDetailReqeuest) ProtoMessage() {}

func (x *GetByIdTransactionDetailReqeuest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_transaction_detail_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetByIdTransactionDetailReqeuest.ProtoReflect.Descriptor instead.
func (*GetByIdTransactionDetailReqeuest) Descriptor() ([]byte, []int) {
	return file_proto_transaction_detail_proto_rawDescGZIP(), []int{7}
}

func (x *GetByIdTransactionDetailReqeuest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type EmptyTransactionDetail struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmptyTransactionDetail) Reset() {
	*x = EmptyTransactionDetail{}
	mi := &file_proto_transaction_detail_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmptyTransactionDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmptyTransactionDetail) ProtoMessage() {}

func (x *EmptyTransactionDetail) ProtoReflect() protoreflect.Message {
	mi := &file_proto_transaction_detail_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmptyTransactionDetail.ProtoReflect.Descriptor instead.
func (*EmptyTransactionDetail) Descriptor() ([]byte, []int) {
	return file_proto_transaction_detail_proto_rawDescGZIP(), []int{8}
}

var File_proto_transaction_detail_proto protoreflect.FileDescriptor

const file_proto_transaction_detail_proto_rawDesc = "" +
	"\n" +
	"\x1eproto/transaction_detail.proto\x12\x12transaction_detail\x1a\x1fgoogle/protobuf/timestamp.proto\"\x97\x02\n" +
	"\x11TransactionDetail\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12%\n" +
	"\x0etransaction_id\x18\x02 \x01(\tR\rtransactionId\x12\x17\n" +
	"\afood_id\x18\x03 \x01(\tR\x06foodId\x12\x14\n" +
	"\x05price\x18\x04 \x01(\x03R\x05price\x12\x10\n" +
	"\x03qty\x18\x05 \x01(\x03R\x03qty\x12\x14\n" +
	"\x05total\x18\x06 \x01(\x03R\x05total\x129\n" +
	"\n" +
	"created_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"w\n" +
	"\x1dTransactionDetailListResponse\x12V\n" +
	"\x13transaction_details\x18\x01 \x03(\v2%.transaction_detail.TransactionDetailR\x12transactionDetails\"\x9f\x01\n" +
	"\x1fCreateTransactionDetailReqeuest\x12%\n" +
	"\x0etransaction_id\x18\x01 \x01(\tR\rtransactionId\x12\x17\n" +
	"\afood_id\x18\x02 \x01(\tR\x06foodId\x12\x14\n" +
	"\x05price\x18\x03 \x01(\x03R\x05price\x12\x10\n" +
	"\x03qty\x18\x04 \x01(\x03R\x03qty\x12\x14\n" +
	"\x05total\x18\x05 \x01(\x03R\x05total\"\xaf\x01\n" +
	"\x1fUpdateTransactionDetailReqeuest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12%\n" +
	"\x0etransaction_id\x18\x02 \x01(\tR\rtransactionId\x12\x17\n" +
	"\afood_id\x18\x03 \x01(\tR\x06foodId\x12\x14\n" +
	"\x05price\x18\x04 \x01(\x03R\x05price\x12\x10\n" +
	"\x03qty\x18\x05 \x01(\x03R\x03qty\x12\x14\n" +
	"\x05total\x18\x06 \x01(\x03R\x05total\"0\n" +
	"\x1eDeleteTransactionDetailRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\";\n" +
	"\x1fDeleteTransactionDetailResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"p\n" +
	"\x19TransactionDetailResponse\x12S\n" +
	"\x11TransactionDetail\x18\x01 \x01(\v2%.transaction_detail.TransactionDetailR\x11TransactionDetail\"2\n" +
	" GetByIdTransactionDetailReqeuest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x18\n" +
	"\x16EmptyTransactionDetail2\x94\x05\n" +
	"\x18TransactionDetailService\x12}\n" +
	"\x17CreateTransactionDetail\x123.transaction_detail.CreateTransactionDetailReqeuest\x1a-.transaction_detail.TransactionDetailResponse\x12t\n" +
	"\x17GetAllTransactionDetail\x12*.transaction_detail.EmptyTransactionDetail\x1a-.transaction_detail.TransactionDetailResponse\x12\x7f\n" +
	"\x18GetByIdTransactionDetail\x124.transaction_detail.GetByIdTransactionDetailReqeuest\x1a-.transaction_detail.TransactionDetailResponse\x12}\n" +
	"\x17UpdateTransactionDetail\x123.transaction_detail.UpdateTransactionDetailReqeuest\x1a-.transaction_detail.TransactionDetailResponse\x12\x82\x01\n" +
	"\x17DeleteTransactionDetail\x122.transaction_detail.DeleteTransactionDetailRequest\x1a3.transaction_detail.DeleteTransactionDetailResponseB\x1eZ\x1cinternal/delivery/grpc/pb;pbb\x06proto3"

var (
	file_proto_transaction_detail_proto_rawDescOnce sync.Once
	file_proto_transaction_detail_proto_rawDescData []byte
)

func file_proto_transaction_detail_proto_rawDescGZIP() []byte {
	file_proto_transaction_detail_proto_rawDescOnce.Do(func() {
		file_proto_transaction_detail_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_transaction_detail_proto_rawDesc), len(file_proto_transaction_detail_proto_rawDesc)))
	})
	return file_proto_transaction_detail_proto_rawDescData
}

var file_proto_transaction_detail_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_proto_transaction_detail_proto_goTypes = []any{
	(*TransactionDetail)(nil),                // 0: transaction_detail.TransactionDetail
	(*TransactionDetailListResponse)(nil),    // 1: transaction_detail.TransactionDetailListResponse
	(*CreateTransactionDetailReqeuest)(nil),  // 2: transaction_detail.CreateTransactionDetailReqeuest
	(*UpdateTransactionDetailReqeuest)(nil),  // 3: transaction_detail.UpdateTransactionDetailReqeuest
	(*DeleteTransactionDetailRequest)(nil),   // 4: transaction_detail.DeleteTransactionDetailRequest
	(*DeleteTransactionDetailResponse)(nil),  // 5: transaction_detail.DeleteTransactionDetailResponse
	(*TransactionDetailResponse)(nil),        // 6: transaction_detail.TransactionDetailResponse
	(*GetByIdTransactionDetailReqeuest)(nil), // 7: transaction_detail.GetByIdTransactionDetailReqeuest
	(*EmptyTransactionDetail)(nil),           // 8: transaction_detail.EmptyTransactionDetail
	(*timestamppb.Timestamp)(nil),            // 9: google.protobuf.Timestamp
}
var file_proto_transaction_detail_proto_depIdxs = []int32{
	9, // 0: transaction_detail.TransactionDetail.created_at:type_name -> google.protobuf.Timestamp
	9, // 1: transaction_detail.TransactionDetail.updated_at:type_name -> google.protobuf.Timestamp
	0, // 2: transaction_detail.TransactionDetailListResponse.transaction_details:type_name -> transaction_detail.TransactionDetail
	0, // 3: transaction_detail.TransactionDetailResponse.TransactionDetail:type_name -> transaction_detail.TransactionDetail
	2, // 4: transaction_detail.TransactionDetailService.CreateTransactionDetail:input_type -> transaction_detail.CreateTransactionDetailReqeuest
	8, // 5: transaction_detail.TransactionDetailService.GetAllTransactionDetail:input_type -> transaction_detail.EmptyTransactionDetail
	7, // 6: transaction_detail.TransactionDetailService.GetByIdTransactionDetail:input_type -> transaction_detail.GetByIdTransactionDetailReqeuest
	3, // 7: transaction_detail.TransactionDetailService.UpdateTransactionDetail:input_type -> transaction_detail.UpdateTransactionDetailReqeuest
	4, // 8: transaction_detail.TransactionDetailService.DeleteTransactionDetail:input_type -> transaction_detail.DeleteTransactionDetailRequest
	6, // 9: transaction_detail.TransactionDetailService.CreateTransactionDetail:output_type -> transaction_detail.TransactionDetailResponse
	6, // 10: transaction_detail.TransactionDetailService.GetAllTransactionDetail:output_type -> transaction_detail.TransactionDetailResponse
	6, // 11: transaction_detail.TransactionDetailService.GetByIdTransactionDetail:output_type -> transaction_detail.TransactionDetailResponse
	6, // 12: transaction_detail.TransactionDetailService.UpdateTransactionDetail:output_type -> transaction_detail.TransactionDetailResponse
	5, // 13: transaction_detail.TransactionDetailService.DeleteTransactionDetail:output_type -> transaction_detail.DeleteTransactionDetailResponse
	9, // [9:14] is the sub-list for method output_type
	4, // [4:9] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_proto_transaction_detail_proto_init() }
func file_proto_transaction_detail_proto_init() {
	if File_proto_transaction_detail_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_transaction_detail_proto_rawDesc), len(file_proto_transaction_detail_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_transaction_detail_proto_goTypes,
		DependencyIndexes: file_proto_transaction_detail_proto_depIdxs,
		MessageInfos:      file_proto_transaction_detail_proto_msgTypes,
	}.Build()
	File_proto_transaction_detail_proto = out.File
	file_proto_transaction_detail_proto_goTypes = nil
	file_proto_transaction_detail_proto_depIdxs = nil
}
