// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: proto/merchant.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Merchant struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	NameMerchant  string                 `protobuf:"bytes,3,opt,name=name_merchant,json=nameMerchant,proto3" json:"name_merchant,omitempty"`
	Lat           string                 `protobuf:"bytes,4,opt,name=lat,proto3" json:"lat,omitempty"`
	Long          string                 `protobuf:"bytes,5,opt,name=long,proto3" json:"long,omitempty"`
	OpenHour      string                 `protobuf:"bytes,6,opt,name=open_hour,json=openHour,proto3" json:"open_hour,omitempty"`
	CloseHour     string                 `protobuf:"bytes,7,opt,name=close_hour,json=closeHour,proto3" json:"close_hour,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Merchant) Reset() {
	*x = Merchant{}
	mi := &file_proto_merchant_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Merchant) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Merchant) ProtoMessage() {}

func (x *Merchant) ProtoReflect() protoreflect.Message {
	mi := &file_proto_merchant_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Merchant.ProtoReflect.Descriptor instead.
func (*Merchant) Descriptor() ([]byte, []int) {
	return file_proto_merchant_proto_rawDescGZIP(), []int{0}
}

func (x *Merchant) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Merchant) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Merchant) GetNameMerchant() string {
	if x != nil {
		return x.NameMerchant
	}
	return ""
}

func (x *Merchant) GetLat() string {
	if x != nil {
		return x.Lat
	}
	return ""
}

func (x *Merchant) GetLong() string {
	if x != nil {
		return x.Long
	}
	return ""
}

func (x *Merchant) GetOpenHour() string {
	if x != nil {
		return x.OpenHour
	}
	return ""
}

func (x *Merchant) GetCloseHour() string {
	if x != nil {
		return x.CloseHour
	}
	return ""
}

func (x *Merchant) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Merchant) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type MerchantListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Merchants     []*Merchant            `protobuf:"bytes,1,rep,name=merchants,proto3" json:"merchants,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MerchantListResponse) Reset() {
	*x = MerchantListResponse{}
	mi := &file_proto_merchant_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MerchantListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MerchantListResponse) ProtoMessage() {}

func (x *MerchantListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_merchant_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MerchantListResponse.ProtoReflect.Descriptor instead.
func (*MerchantListResponse) Descriptor() ([]byte, []int) {
	return file_proto_merchant_proto_rawDescGZIP(), []int{1}
}

func (x *MerchantListResponse) GetMerchants() []*Merchant {
	if x != nil {
		return x.Merchants
	}
	return nil
}

type CreateMerchantReqeuest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	NameMerchant  string                 `protobuf:"bytes,2,opt,name=name_merchant,json=nameMerchant,proto3" json:"name_merchant,omitempty"`
	Lat           string                 `protobuf:"bytes,3,opt,name=lat,proto3" json:"lat,omitempty"`
	Long          string                 `protobuf:"bytes,4,opt,name=long,proto3" json:"long,omitempty"`
	OpenHour      string                 `protobuf:"bytes,5,opt,name=open_hour,json=openHour,proto3" json:"open_hour,omitempty"`
	CloseHour     string                 `protobuf:"bytes,6,opt,name=close_hour,json=closeHour,proto3" json:"close_hour,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateMerchantReqeuest) Reset() {
	*x = CreateMerchantReqeuest{}
	mi := &file_proto_merchant_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateMerchantReqeuest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateMerchantReqeuest) ProtoMessage() {}

func (x *CreateMerchantReqeuest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_merchant_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateMerchantReqeuest.ProtoReflect.Descriptor instead.
func (*CreateMerchantReqeuest) Descriptor() ([]byte, []int) {
	return file_proto_merchant_proto_rawDescGZIP(), []int{2}
}

func (x *CreateMerchantReqeuest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CreateMerchantReqeuest) GetNameMerchant() string {
	if x != nil {
		return x.NameMerchant
	}
	return ""
}

func (x *CreateMerchantReqeuest) GetLat() string {
	if x != nil {
		return x.Lat
	}
	return ""
}

func (x *CreateMerchantReqeuest) GetLong() string {
	if x != nil {
		return x.Long
	}
	return ""
}

func (x *CreateMerchantReqeuest) GetOpenHour() string {
	if x != nil {
		return x.OpenHour
	}
	return ""
}

func (x *CreateMerchantReqeuest) GetCloseHour() string {
	if x != nil {
		return x.CloseHour
	}
	return ""
}

type UpdateMerchantReqeuest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	NameMerchant  string                 `protobuf:"bytes,3,opt,name=name_merchant,json=nameMerchant,proto3" json:"name_merchant,omitempty"`
	Lat           string                 `protobuf:"bytes,4,opt,name=lat,proto3" json:"lat,omitempty"`
	Long          string                 `protobuf:"bytes,5,opt,name=long,proto3" json:"long,omitempty"`
	OpenHour      string                 `protobuf:"bytes,6,opt,name=open_hour,json=openHour,proto3" json:"open_hour,omitempty"`
	CloseHour     string                 `protobuf:"bytes,7,opt,name=close_hour,json=closeHour,proto3" json:"close_hour,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateMerchantReqeuest) Reset() {
	*x = UpdateMerchantReqeuest{}
	mi := &file_proto_merchant_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateMerchantReqeuest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateMerchantReqeuest) ProtoMessage() {}

func (x *UpdateMerchantReqeuest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_merchant_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateMerchantReqeuest.ProtoReflect.Descriptor instead.
func (*UpdateMerchantReqeuest) Descriptor() ([]byte, []int) {
	return file_proto_merchant_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateMerchantReqeuest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateMerchantReqeuest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UpdateMerchantReqeuest) GetNameMerchant() string {
	if x != nil {
		return x.NameMerchant
	}
	return ""
}

func (x *UpdateMerchantReqeuest) GetLat() string {
	if x != nil {
		return x.Lat
	}
	return ""
}

func (x *UpdateMerchantReqeuest) GetLong() string {
	if x != nil {
		return x.Long
	}
	return ""
}

func (x *UpdateMerchantReqeuest) GetOpenHour() string {
	if x != nil {
		return x.OpenHour
	}
	return ""
}

func (x *UpdateMerchantReqeuest) GetCloseHour() string {
	if x != nil {
		return x.CloseHour
	}
	return ""
}

type DeleteMerchantRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteMerchantRequest) Reset() {
	*x = DeleteMerchantRequest{}
	mi := &file_proto_merchant_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteMerchantRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteMerchantRequest) ProtoMessage() {}

func (x *DeleteMerchantRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_merchant_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteMerchantRequest.ProtoReflect.Descriptor instead.
func (*DeleteMerchantRequest) Descriptor() ([]byte, []int) {
	return file_proto_merchant_proto_rawDescGZIP(), []int{4}
}

func (x *DeleteMerchantRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteMerchantResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteMerchantResponse) Reset() {
	*x = DeleteMerchantResponse{}
	mi := &file_proto_merchant_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteMerchantResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteMerchantResponse) ProtoMessage() {}

func (x *DeleteMerchantResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_merchant_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteMerchantResponse.ProtoReflect.Descriptor instead.
func (*DeleteMerchantResponse) Descriptor() ([]byte, []int) {
	return file_proto_merchant_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteMerchantResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type MerchantResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Merchant      *Merchant              `protobuf:"bytes,1,opt,name=Merchant,proto3" json:"Merchant,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MerchantResponse) Reset() {
	*x = MerchantResponse{}
	mi := &file_proto_merchant_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MerchantResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MerchantResponse) ProtoMessage() {}

func (x *MerchantResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_merchant_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MerchantResponse.ProtoReflect.Descriptor instead.
func (*MerchantResponse) Descriptor() ([]byte, []int) {
	return file_proto_merchant_proto_rawDescGZIP(), []int{6}
}

func (x *MerchantResponse) GetMerchant() *Merchant {
	if x != nil {
		return x.Merchant
	}
	return nil
}

type GetByIdMerchantReqeuest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetByIdMerchantReqeuest) Reset() {
	*x = GetByIdMerchantReqeuest{}
	mi := &file_proto_merchant_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetByIdMerchantReqeuest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetByIdMerchantReqeuest) ProtoMessage() {}

func (x *GetByIdMerchantReqeuest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_merchant_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetByIdMerchantReqeuest.ProtoReflect.Descriptor instead.
func (*GetByIdMerchantReqeuest) Descriptor() ([]byte, []int) {
	return file_proto_merchant_proto_rawDescGZIP(), []int{7}
}

func (x *GetByIdMerchantReqeuest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_proto_merchant_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_proto_merchant_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_proto_merchant_proto_rawDescGZIP(), []int{8}
}

var File_proto_merchant_proto protoreflect.FileDescriptor

const file_proto_merchant_proto_rawDesc = "" +
	"\n" +
	"\x14proto/merchant.proto\x12\bmerchant\x1a\x1fgoogle/protobuf/timestamp.proto\"\xb0\x02\n" +
	"\bMerchant\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12#\n" +
	"\rname_merchant\x18\x03 \x01(\tR\fnameMerchant\x12\x10\n" +
	"\x03lat\x18\x04 \x01(\tR\x03lat\x12\x12\n" +
	"\x04long\x18\x05 \x01(\tR\x04long\x12\x1b\n" +
	"\topen_hour\x18\x06 \x01(\tR\bopenHour\x12\x1d\n" +
	"\n" +
	"close_hour\x18\a \x01(\tR\tcloseHour\x129\n" +
	"\n" +
	"created_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"H\n" +
	"\x14MerchantListResponse\x120\n" +
	"\tmerchants\x18\x01 \x03(\v2\x12.merchant.MerchantR\tmerchants\"\xb8\x01\n" +
	"\x16CreateMerchantReqeuest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12#\n" +
	"\rname_merchant\x18\x02 \x01(\tR\fnameMerchant\x12\x10\n" +
	"\x03lat\x18\x03 \x01(\tR\x03lat\x12\x12\n" +
	"\x04long\x18\x04 \x01(\tR\x04long\x12\x1b\n" +
	"\topen_hour\x18\x05 \x01(\tR\bopenHour\x12\x1d\n" +
	"\n" +
	"close_hour\x18\x06 \x01(\tR\tcloseHour\"\xc8\x01\n" +
	"\x16UpdateMerchantReqeuest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12#\n" +
	"\rname_merchant\x18\x03 \x01(\tR\fnameMerchant\x12\x10\n" +
	"\x03lat\x18\x04 \x01(\tR\x03lat\x12\x12\n" +
	"\x04long\x18\x05 \x01(\tR\x04long\x12\x1b\n" +
	"\topen_hour\x18\x06 \x01(\tR\bopenHour\x12\x1d\n" +
	"\n" +
	"close_hour\x18\a \x01(\tR\tcloseHour\"'\n" +
	"\x15DeleteMerchantRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"2\n" +
	"\x16DeleteMerchantResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"B\n" +
	"\x10MerchantResponse\x12.\n" +
	"\bMerchant\x18\x01 \x01(\v2\x12.merchant.MerchantR\bMerchant\")\n" +
	"\x17GetByIdMerchantReqeuest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\a\n" +
	"\x05Empty2\x97\x03\n" +
	"\x0fMerchantService\x12N\n" +
	"\x0eCreateMerchant\x12 .merchant.CreateMerchantReqeuest\x1a\x1a.merchant.MerchantResponse\x12=\n" +
	"\x0eGetAllMerchant\x12\x0f.merchant.Empty\x1a\x1a.merchant.MerchantResponse\x12P\n" +
	"\x0fGetByIdMerchant\x12!.merchant.GetByIdMerchantReqeuest\x1a\x1a.merchant.MerchantResponse\x12N\n" +
	"\x0eUpdateMerchant\x12 .merchant.UpdateMerchantReqeuest\x1a\x1a.merchant.MerchantResponse\x12S\n" +
	"\x0eDeleteMerchant\x12\x1f.merchant.DeleteMerchantRequest\x1a .merchant.DeleteMerchantResponseB\x1eZ\x1cinternal/delivery/grpc/pb;pbb\x06proto3"

var (
	file_proto_merchant_proto_rawDescOnce sync.Once
	file_proto_merchant_proto_rawDescData []byte
)

func file_proto_merchant_proto_rawDescGZIP() []byte {
	file_proto_merchant_proto_rawDescOnce.Do(func() {
		file_proto_merchant_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_merchant_proto_rawDesc), len(file_proto_merchant_proto_rawDesc)))
	})
	return file_proto_merchant_proto_rawDescData
}

var file_proto_merchant_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_proto_merchant_proto_goTypes = []any{
	(*Merchant)(nil),                // 0: merchant.Merchant
	(*MerchantListResponse)(nil),    // 1: merchant.MerchantListResponse
	(*CreateMerchantReqeuest)(nil),  // 2: merchant.CreateMerchantReqeuest
	(*UpdateMerchantReqeuest)(nil),  // 3: merchant.UpdateMerchantReqeuest
	(*DeleteMerchantRequest)(nil),   // 4: merchant.DeleteMerchantRequest
	(*DeleteMerchantResponse)(nil),  // 5: merchant.DeleteMerchantResponse
	(*MerchantResponse)(nil),        // 6: merchant.MerchantResponse
	(*GetByIdMerchantReqeuest)(nil), // 7: merchant.GetByIdMerchantReqeuest
	(*Empty)(nil),                   // 8: merchant.Empty
	(*timestamppb.Timestamp)(nil),   // 9: google.protobuf.Timestamp
}
var file_proto_merchant_proto_depIdxs = []int32{
	9, // 0: merchant.Merchant.created_at:type_name -> google.protobuf.Timestamp
	9, // 1: merchant.Merchant.updated_at:type_name -> google.protobuf.Timestamp
	0, // 2: merchant.MerchantListResponse.merchants:type_name -> merchant.Merchant
	0, // 3: merchant.MerchantResponse.Merchant:type_name -> merchant.Merchant
	2, // 4: merchant.MerchantService.CreateMerchant:input_type -> merchant.CreateMerchantReqeuest
	8, // 5: merchant.MerchantService.GetAllMerchant:input_type -> merchant.Empty
	7, // 6: merchant.MerchantService.GetByIdMerchant:input_type -> merchant.GetByIdMerchantReqeuest
	3, // 7: merchant.MerchantService.UpdateMerchant:input_type -> merchant.UpdateMerchantReqeuest
	4, // 8: merchant.MerchantService.DeleteMerchant:input_type -> merchant.DeleteMerchantRequest
	6, // 9: merchant.MerchantService.CreateMerchant:output_type -> merchant.MerchantResponse
	6, // 10: merchant.MerchantService.GetAllMerchant:output_type -> merchant.MerchantResponse
	6, // 11: merchant.MerchantService.GetByIdMerchant:output_type -> merchant.MerchantResponse
	6, // 12: merchant.MerchantService.UpdateMerchant:output_type -> merchant.MerchantResponse
	5, // 13: merchant.MerchantService.DeleteMerchant:output_type -> merchant.DeleteMerchantResponse
	9, // [9:14] is the sub-list for method output_type
	4, // [4:9] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_proto_merchant_proto_init() }
func file_proto_merchant_proto_init() {
	if File_proto_merchant_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_merchant_proto_rawDesc), len(file_proto_merchant_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_merchant_proto_goTypes,
		DependencyIndexes: file_proto_merchant_proto_depIdxs,
		MessageInfos:      file_proto_merchant_proto_msgTypes,
	}.Build()
	File_proto_merchant_proto = out.File
	file_proto_merchant_proto_goTypes = nil
	file_proto_merchant_proto_depIdxs = nil
}
